export interface Info {
  id?: number,
  url: string,
  status: string,
  cartridge: any,
  client_id: number,
  productname: string,
  printcycles: number,
  scancycles: number,
  log: any,
  kit: string,
  company_id: number,
  address_id: number,
  serialnumber: string,
  maintenancekitcount: string,
  adfcycles: number,
  article: string,
  client_article: string,
  datetime: any
}
